version: '3'

volumes:
  data:

services:
  singers-bot:
    build:
      context: .
      dockerfile: SingersDockerfile

    volumes:
      - data:/app/data

  trio-bot:
    build:
      context: .
      dockerfile: TrioDockerfile
    volumes:
      - data:/app/data
